### PR TITLE
Fixes for Non-Optional Crash and iOS Comp

### PR DESCRIPTION
**Pull request by DIntriglia**
[FIX] Converted substr to prefix for iv.
[FIX] Data was not optional, so would crash app on load. Fixed by using a optional check, and default value.

### CODE REVIEW

**Comment by skreutzberger** [comment]
Thanks! please let the function return "" on error. Also if the String prefix fix is just working on Swift 4 then please use a compiler switch like this https://github.com/SwiftyBeaver/SwiftyBeaver/blob/master/Sources/BaseDestination.swift#L291

**Comment by Djimusic** [comment]
I can definitely return “” as that makes more sense. The String prefix fix is to stop the yellow warning flag on compile with iOS 11, but works on anything prior to 11 as well. I will make the “” change, and resubmit the merge request.

-Dakotah

**Comment by skreutzberger** [comment]
Great! Does it also work on Swift 3.1? I know there were changes between 3.1 and 3.2 / 4.0 and a lot users still are running on Swift 3.1

**Comment by skreutzberger** [comment]
Somehow CircleCI never finished that issue. Can you please submit a small change or so so that CircleCI can run again?

**Comment by EliteTechnicalCare** [comment]
Please push this change

**Comment by skreutzberger** [comment]
pushed 🚀

**Pull request merged**
